---
- name: Installer Apache2 et Git + PHP et extensions
  ansible.builtin.apt:
    name:
      - apache2
      - git
      - php
      - php-mysql
      - libapache2-mod-php
    state: present
    update_cache: true

- name: Assurer que Apache est actif
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true


- name: Supprimer l'ancien répertoire webapp
  ansible.builtin.file:
    path: "{{ web_app_dest }}"
    state: absent

- name: Créer le répertoire webapp
  ansible.builtin.file:
    path: "{{ web_app_dest }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Cloner la webapp depuis Git
  ansible.builtin.git:
    repo: "{{ web_app_repo }}"
    dest: "{{ web_app_dest }}"
    version: main
    force: true

- name: Déployer le VirtualHost Apache
  ansible.builtin.template:
    src: virtualhost.conf.j2
    dest: /etc/apache2/sites-available/webapp.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache

- name: Vérifier si le VirtualHost est déjà activé
  ansible.builtin.stat:
    path: /etc/apache2/sites-enabled/webapp.conf
  register: web_site_enabled


- name: Activer le VirtualHost via a2ensite si nécessaire
  ansible.builtin.command: a2ensite webapp.conf
  when: not web_site_enabled.stat.exists
  changed_when: false
  notify: Restart Apache

- name: Vérifier si 000-default.conf est activé
  ansible.builtin.stat:
    path: /etc/apache2/sites-enabled/000-default.conf
  register: web_default_enabled

- name: Désactiver 000-default.conf avec a2dissite si nécessaire
  ansible.builtin.command: a2dissite 000-default.conf
  when: web_default_enabled.stat.exists
  changed_when: false
  notify: Restart Apache


- name: Vérifier qu'Apache répond
  ansible.builtin.uri:
    url: http://localhost
    return_content: true
  register: web_apache_check

- name: Debug statut HTTP Apache
  ansible.builtin.debug:
    msg: "Apache répond avec le code HTTP {{ web_apache_check.status }}"
