$ANSIBLE_VAULT;1.1;AES256
32373137376465383165356130386530333934323666643164623864333765393262633637653464
6532383230386131333432333130643437303838343634300a313665633931376437633935343032
62396433656564633032313031653133323330656332383937313261653564333465666330363631
6664363763646335360a356232353538306439386435383861323633303830666166663932343531
35363264383135663236316634356366303065303131386163373731643934303937326336393662
39386133616530323562306164643531623633376138396136666135666430313239303433346663
62386338373932316539356330303437666166373130386264623533663364613162326661633532
34343632303530373662623132383535396664333538303139363265303733343166356666363030
31333034636434636664343634643437383031643432613134373136373861336263366266663238
39636633633565336232333361643434663437336537373762363138303936363032353133663338
63633562643362646631643938666665313562376538353163333464346365633531323531643730
39656462303761613964
