---
- name: Déploiement webapp
  hosts: appservers
  become: true
  gather_facts: false

  vars:
    html_dest: "/var/www/html"

  tasks:
    - name: Mise à jour
      ansible.builtin.apt:
        update_cache: true

    - name: Installer Apache2 et Git
      ansible.builtin.apt:
        name:
          - apache2
          - git
        state: present
        update_cache: true


    - name: Supprimer l’index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    # task git ici

    - name: Vérif le status Apache
      ansible.builtin.systemd:
        name: apache2
        state: started
