---
- name: Configuration commune
  hosts: all
  become: true
  roles:
    - common

- name: Déploiement web
  hosts: webservers
  become: true
  roles:
    - web
    - openvpn

- name: Déploiement base de données
  hosts: dbservers
  become: true
  roles:
    - db
